import test from 'node:test';
import assert from 'node:assert/strict';
import { createSplitService, participantView } from '../supabase/functions/split-bill/handler.mjs';
import { pizza } from './fixtures/split-bill.mjs';

const owner='00000000-0000-4000-8000-000000000001',account='00000000-0000-4000-8000-000000000002',category='00000000-0000-4000-8000-000000000003';
function database(){
  const rows={accounts:[{id:account,user_id:owner,is_active:true}],categories:[{id:category,user_id:owner,type:'expense',is_active:true}],split_bills:[],transactions:[],notifications:[]};
  const db={rows,storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://example.test/proof'}}),upload:async()=>({}),remove:async()=>({})})},
    from(table){let result=rows[table];const q={select(){return q;},eq(k,v){result=result.filter(r=>r[k]===v);return q;},is(k,v){result=result.filter(r=>(r[k]??null)===v);return q;},order(){return q;},limit(){return q;},single:async()=>({data:result[0],error:result.length?null:{message:'not found'}}),then(resolve){resolve({data:result,error:null});}};return q;},
    async rpc(name,p){const existing=rows.split_bills.find(r=>r.id===p.p_id);
      if(name==='cancel_split_bill') {if(existing?.revision!==p.p_expected)return{error:{message:'changed'}};existing.document.cancelled=true;existing.revision++;rows.transactions=rows.transactions.filter(t=>t.split_bill_id!==p.p_id);return{};}if(p.p_expected!==0 && existing?.revision!==p.p_expected)return{error:{message:'changed'}};const revision=(existing?.revision || 0)+1;const row={id:p.p_id,user_id:p.p_owner,document:structuredClone(p.p_document),revision};if(existing)Object.assign(existing,row);else rows.split_bills.push(row);rows.transactions.push(...p.p_rows.map(t=>({...t,user_id:p.p_owner,split_bill_id:p.p_id})));return{data:revision};}};return db;
}
async function setup(){const db=database(),run=createSplitService(db),bill=pizza();bill.accountId=account;bill.categoryId=category;const created=(await run({action:'create',bill},owner)).bill;return{db,run,b:created};}
test('owner creates ledger spending 30 and cash paid 125 atomically',async()=>{const{db,b}=await setup();assert.equal(db.rows.transactions[0].report_amount,30);assert.equal(db.rows.transactions[0].cash_amount,125);assert.equal(b.revision,1);});
test('retrying the same draft does not duplicate the cash or spending entry',async()=>{const db=database(),run=createSplitService(db),bill={...pizza(),id:crypto.randomUUID(),accountId:account,categoryId:category};const first=await run({action:'create',bill},owner),retry=await run({action:'create',bill},owner);assert.equal(first.bill.id,retry.bill.id);assert.equal(db.rows.transactions.length,1);});
test('private link scopes view and recipient confirmation, with partial settlement',async()=>{let{db,run,b}=await setup();const link=await run({action:'link',id:b.id,revision:b.revision,participantId:'b'},owner);b=link.bill;const token=link.token;const v=(await run({action:'get',id:b.id,token})).view;assert.equal(v.person.share,3000);assert.equal(v.items.length,3);assert.equal(v.participants.some(p=>p.id==='d'),false);assert.equal(JSON.stringify(v).includes('tokenHash'),false);
  const reported=await run({action:'report',id:b.id,token,revision:b.revision,payment:{id:'p1',from:'b',to:'a',cents:1000,date:b.date,proofPath:'private/stolen-receipt'}},null);assert.equal(reported.view.payments[0].proofPath,null);b=(await run({action:'get',id:b.id},owner)).bill;
  await assert.rejects(()=>run({action:'decision',id:b.id,token,revision:b.revision,paymentId:'p1',decision:'confirmed'}),/recipient/);
  b=(await run({action:'decision',id:b.id,revision:b.revision,paymentId:'p1',decision:'confirmed',accountId:account},owner)).bill;
  assert.equal(db.rows.transactions.at(-1).report_amount,0);assert.equal(db.rows.transactions.at(-1).cash_amount,10);assert.equal(b.payments[0].confirmedBy,'owner');
});
test('rotating participant link revokes old access',async()=>{let{run,b}=await setup();const old=await run({action:'link',id:b.id,revision:b.revision,participantId:'b'},owner);const fresh=await run({action:'link',id:b.id,revision:old.bill.revision,participantId:'b'},owner);await assert.rejects(()=>run({action:'get',id:b.id,token:old.token}),/invalid/);assert.equal((await run({action:'get',id:b.id,token:fresh.token})).view.participantId,'b');});
test('stale revision and unauthorized owner reads are rejected',async()=>{const{run,b}=await setup();await assert.rejects(()=>run({action:'link',id:b.id,revision:0,participantId:'b'},owner),/changed/);await assert.rejects(()=>run({action:'get',id:b.id},'someone-else'),/invalid/);});
test('repayment plan is locked after a report',async()=>{const{run,b}=await setup();const r=await run({action:'report',id:b.id,revision:b.revision,payment:{id:'p',from:'b',to:'a',cents:100,date:b.date}},owner);await assert.rejects(()=>run({action:'plan',id:b.id,revision:r.bill.revision,plan:b.plan},owner),/locked/);});
test('cancel removes generated financial entries and invalidates participant access',async()=>{const{db,run,b}=await setup();const l=await run({action:'link',id:b.id,revision:b.revision,participantId:'b'},owner);await assert.rejects(()=>run({action:'cancel',id:b.id,token:l.token,revision:l.bill.revision}),/creator/);await run({action:'cancel',id:b.id,revision:l.bill.revision},owner);assert.equal(db.rows.transactions.length,0);assert.equal((await run({action:'list'},owner)).bills.length,0);await assert.rejects(()=>run({action:'get',id:b.id,token:l.token}),/cancelled/);});
test('cancel is blocked once a repayment is reported',async()=>{const{run,b}=await setup();const r=await run({action:'report',id:b.id,revision:b.revision,payment:{id:'p',from:'b',to:'a',cents:100,date:b.date}},owner);await assert.rejects(()=>run({action:'cancel',id:b.id,revision:r.bill.revision},owner),/Cannot cancel/);});
test('recipient other than owner can confirm incoming payments',async()=>{let{run,b}=await setup();const create=pizza();create.accountId=account;create.categoryId=category;create.paid=[{id:'p1',participantId:'a',cents:7500},{id:'p2',participantId:'b',cents:5000}];b=(await run({action:'create',bill:create},owner)).bill;const link=await run({action:'link',id:b.id,revision:b.revision,participantId:'b'},owner);b=link.bill;const line=b.plan.find(l=>l.to==='b');const r=await run({action:'report',id:b.id,revision:b.revision,payment:{id:'p',from:line.from,to:line.to,cents:line.cents,date:b.date}},owner);const result=await run({action:'decision',id:b.id,token:link.token,revision:r.bill.revision,paymentId:'p',decision:'confirmed'});assert.equal(result.view.payments[0].confirmedBy,'b');});
